### ISSUE TITLE
Mod will not load in Custom Map Editor

### ISSUE THREAD

**Issue by ZoLatKam** [CyaNox/Noxys_Waterfill#3]
After adjusting all the sliders for the map, when loading into edit mode, the following error appears & I must disable the 2 mods listed in order to continue:

![ZLK Skrnsht2618_24 07 2020_215421](https://user-images.githubusercontent.com/37105289/88468385-66a2e300-cea8-11ea-9558-c2afb45a5d7f.png)

I can provide any log files or an image of the list of the mods I'm currently using upon request.

**Comment by NoxyNixie** [comment]
This is most likely because of a mod (Alien Biomes, Space Exploration or any other) disabling green water. Either disable the option to add green water fill in my settings or disable the option that makes ther other mod (Alien Biomes) remove unused tiles.

For reference here is a related discussion: https://mods.factorio.com/mod/Noxys_Waterfill/discussion/5d93243d7d42c6000d0f96d0
